const translations = {
  en: {
    menu: 'menu',
    about: 'about',
    news: 'news',
    contact: 'contact',
    festival: 'festival',
    footermediap: 'For media inquiries and press-related matters please reach out to press@moods.com.en ',
    copyright: '2025 Moods. All Rights Reserved.',
    privacy: 'privacy policy',
    cookie: 'cookie policy',
    use: 'Terms of use',
    contact: 'contact us',
    contactCaption: 'To get in touch with the Moods team simply fill out the contact form below. Alternatively, you can telephone us on 0105 010 8006 or email us at moods.resturant.cafe@gmail.com. Address:23 July Street, Behind the Police Club,Qena City, Qena Governorate, Egypt'
    , send: 'send',
    getHere: 'To Get Here',
    getHereCaption: 'Moods Restaurant is located in the heart of Qena city, specifically on 23 July Street behindthe Police Club.The place is easy to reach whether you\'re driving or walking, and it\'s near key landmarks.If you\'re coming from Al- Saa\'a Square, head towards the Police Club and you\'ll find the restaurant on your left.The sign is clear, and the restaurant stands out with its modern interior and exterior design.It\'s spacious and comfortable, perfect for families and groups, with both indoor and outdoor seating areas. The surrounding area is safe and lively, especially in the evenings. Parking is available nearby, making it convenient for guests arriving by car. The restaurant is also accessible for individuals with special needs. Nearby shops and cafes create a welcoming atmosphere. Whether it\'s your first visit or you\'re a regular, getting to Moods is always hassle-free.',
    open: 'Open at',
    close: 'Close at',
    am: 'am',
    pm: 'pm',
    saturday: 'saturday',
    sunday: 'sunday',
    monday: 'monday',
    tuesday: 'tuesday',
    wednsday: 'wednsday',
    thursday: 'thursday',
    friday: 'friday',
    working: 'Working',
    ours: 'hours',
    share: 'Share your dining experience with us',
    yourReview: 'Leave Your Review',
    yourName: 'Your Name',
    email: 'Email Address',
    rating: 'Your Rating',
    experience: 'Your Experience',
    submitReview: 'Submit Review',
    testimonials: 'Testimonials',
    noTestimonials: 'No testimonials yet. Be the first to share your experience!'
    , welcomeToMoods: 'Welcome to fast food at moods',
    enjoyOurMeals: 'Enjoy our delicious meal',
    exploreMore: 'Explore more',
    bestQuality: 'Best quality food',
    orderNow: 'Order Now',
    eastyToOrder: 'Easy to Order',
    orderP: 'You only need few steps in ordering food',
    fastestDelivery: 'Fastest Delivery',
    deliveryP: 'Delivery that\'s always on time, even faster',
    goodQuality: 'Good Quality',
    qualityP: 'Not only fast — for us, quality is number one',
    testimonialsP: 'Our customers love the Moods experience — from the mouthwatering meals to the warm, welcoming atmosphere. Every dish is crafted with care, and it shows in the smiles of those who dine with us. Whether you\'re here for a quick bite or a family gathering, Moods is where great food meets great memories.'
    , noTestimonials: 'No reviews yet. Be the first to share your experience!'
    , ourServ: 'Our Serv',
    Ices: 'ices',
    servicesP: 'At Moods, we cater to every preference with thoughtfully designed spaces. Whether you prefer the elegance and comfort of our Close Area, the vibrant ambiance of our Open Area, or the iconic charm of the main Moods Restaurant, there\'s a perfect spot for everyone. Families with little ones can also enjoy peace of mind in our fun and secure Kids Area — a place designed to keep children happy while you relax and dine. Every corner at Moods is crafted to offer a memorable dining experience.',
    closeArea: 'Close Area',
    openArea: 'Open Area',
    kidsArea: 'Kids Area',
    welcomeToMoods: 'Welcome to fast food at moods',
    enjoyOurMeals: 'Enjoy our delicious meal',
    exploreMore: 'Explore more',
    bestQuality: 'Best quality food',
    seyami: 'seyami',
    fattah: 'fattah',
    sandwitchs: 'sandwitchs',
    meal: 'meal',
    rizo: 'rizo',
    potato: 'potato',
    sauces: 'sauces',
    desserts: 'desserts',
    burger: 'burger',
    wrap: 'wrap',
    chicken: 'chicken',
    chickenMeals: 'Chicken Meals',
    stirpsMeals: 'Stirps Meals',
    kidsMeals: 'Kids Meals',
    healthyMeals: 'Healthy Meals',
    clear: 'Clear All Filters',
    home: 'home',
    reviews: 'Reviews',
    landing: 'Save the moment',
    landingP: 'Your spot for fast food & desserts',
    welcome: 'Welcome to Moods',
    welcomeP: 'Your perfect spot for fast meals, refreshing juices, and sweet desserts – all in one place.',
    location: 'Our Location',
    Categories: 'Our Categories',
    view: 'view',
    popular: 'Popular'
  },
  ar: {
    menu: 'منيو',
    about: 'حول',
    news: 'الاخبار',
    contact: 'التواصل',
    festival: 'الاحتفالات',
    footermediap: ' press@moods.com.en للاستفسارات الإعلامية والمسائل المتعلقة بالصحافة، يرجى التواصل مع',
    copyright: ' جميع الحقوق محفوظة لدى Moods 2025',
    privacy: 'privacy policy',
    cookie: 'cookie policy',
    use: 'Terms of use',
    contact: 'تواصل معانا',
    contactCaption: 'للتواصل مع فريق مودز، يُرجى تعبئة نموذج الاتصال أدناه. أو يمكنكم الاتصال بنا على الرقم 01050108006 أو مراسلتنا عبر البريد الإلكتروني moods.resturant.cafe@gmail.com. العنوان: شارع 23 يوليو، خلف نادي الشرطة، مدينة قنا، محافظة قنا، مصر.'
    , send: 'ارسل',
    getHere: 'لكي تأتي هنا',
    getHereCaption: 'يقع مطعم مودز في قلب مدينة قنا، وتحديدًا في شارع ٢٣ يوليو خلف نادي الشرطة. يسهل الوصول إليه بالسيارة أو سيرًا على الأقدام، وهو قريب من أهم المعالم. إذا كنت قادمًا من ميدان الساعة، اتجه نحو نادي الشرطة وستجد المطعم على يسارك. اللافتة واضحة، ويتميز المطعم بتصميمه الداخلي والخارجي العصري. يتميز المطعم بمساحته الواسعة والمريحة، وهو مثالي للعائلات والمجموعات، مع مناطق جلوس داخلية وخارجية. المنطقة المحيطة آمنة وحيوية، خاصةً في المساء. تتوفر مواقف سيارات قريبة، مما يجعله مناسبًا للضيوف القادمين بالسيارة. كما أن المطعم مناسب لذوي الاحتياجات الخاصة. تخلق المتاجر والمقاهي القريبة أجواءً ترحيبية. سواء كانت زيارتك الأولى أو كنت من رواد المطعم الدائمين، فإن الوصول إلى مودز دائمًا سهل وبسيط.'
    , open: 'يفتح في',
    close: 'يغلق في',
    am: 'ص',
    pm: 'م',
    saturday: 'السبت',
    sunday: 'الاحد',
    monday: 'الاثنين',
    tuesday: 'الثلاثاء',
    wednsday: 'الاربع',
    thursday: 'الخميس',
    friday: 'الجمعة ',
    working: 'ساعات',
    hours: 'العمل',
    yourReview: 'قولنا رأيك',
    yourName: 'الاسم',
    email: 'البريد الالكتروني',
    rating: 'التقييم',
    experience: 'تجربتك',
    submitReview: 'ارسل المراجعة',
    testimonials: 'اراء العملاء',
    noTestimonials: 'لا يوجد اراء حاليًا. كن اول من يضع رأيه',
    testimonialsP: 'Our customers love the Moods experience — from the mouthwatering meals to the warm, welcoming atmosphere.Every dish is crafted with care, and it shows in the smiles of those who dine with us.Whether you\'re here for a quick bite or a family gathering, Moods is where great food meets great memories.',
    ourServ: 'خدما',
    Ices: 'تنا',
    servicesP: 'في مودز، نلبي جميع الأذواق بمساحات مصممة بعناية. سواءً كنتم تفضلون أناقة وراحة منطقتنا المغلقة، أو أجواء منطقتنا المفتوحة النابضة بالحياة، أو سحر مطعم مودز الرئيسي المميز، ستجدون المكان المثالي للجميع. كما يمكن للعائلات التي لديها أطفال صغار الاستمتاع براحة البال في منطقة الأطفال الممتعة والآمنة - مكان مصمم لإسعاد الأطفال أثناء استرخائكم وتناول الطعام. كل ركن في مودز مصمم ليقدم لكم تجربة طعام لا تُنسى.',
    closeArea: 'منطقة مغلقة',
    openArea: 'منطقة مفتوحة',
    kidsArea: 'منطقة الاطفال',
    welcomeToMoods: 'اهلا بك في مودز',
    enjoyOurMeals: 'استمتع بوجبتك اللذيذة',
    exploreMore: 'اسكتشف اكثر',
    bestQuality: 'افضل جودة طعام',
    orderNow: 'اطلب الأن',
    eastyToOrder: 'اطلب بسهولة',
    orderP: 'انت فقط تحتاج الى خطوات بسيطة للطلب',
    fastestDelivery: 'سرعة التوصيل',
    deliveryP: 'التسليم دائمًا في الموعد المحدد، وأسرع',
    goodQuality: 'جودة ممتازة',
    qualityP: 'ليس فقط السرعة - بالنسبة لنا، الجودة هي رقم واحد',
    testimonialsP: 'يحب عملاؤنا تجربة Moods - من الوجبات الشهية إلى الأجواء الدافئة والترحيبية. يتم إعداد كل طبق بعناية، ويظهر ذلك في ابتسامات أولئك الذين يتناولون الطعام معنا. سواء كنت هنا لتناول وجبة سريعة أو تجمع عائلي، فإن Moods هو المكان الذي يلتقي فيه الطعام الرائع بالذكريات الرائعة.',
    seyami: 'صيامي',
    fattah: 'فتة',
    sandwitchs: 'ساندوتشات',
    meal: 'وجبات',
    rizo: 'ريزو',
    potato: 'بطاطس',
    sauces: 'صوصات',
    desserts: 'حلوى',
    burger: 'برغر',
    wrap: 'راب',
    chicken: 'فراخ',
    chickenMeals: 'وجبات فراخ',
    stirpsMeals: 'وجبات ستربس',
    kidsMeals: 'وجبات اطفال',
    healthyMeals: 'وجبات صحية',
    clear: 'ازالة جميع المرشحات',
    home: 'الصفحة الرئيسية',
    reviews: 'اراَء',
    landing: 'عيش اللحظة',
    landingP: 'مكانك للاكل السريع والحلاويات',
    welcome: 'اهلا بك في Moods',
    welcomeP: 'مكانك المثالي للوجبات السريعة والعصائر المنعشة والحلويات الحلوة - كل ذلك في مكان واحد.',
    location: 'مكاننا',
    Categories: 'الاصناف',
    sandwichesP: 'Juicy beef & chicken burgers with fresh toppings.',
    view: 'انظر',
    popular: 'الاكثر طلبًا',
  }
};

function updateContent(lang) {
  document.documentElement.setAttribute("lang", lang);
  document.documentElement.setAttribute("dir", lang === "ar" ? "rtl" : "ltr");
  document.querySelectorAll("[data-i18n]").forEach(element => {
    const key = element.getAttribute("data-i18n");
    element.textContent = translations[lang][key] || element.textContent;
  });
  const langBtn = document.querySelector(".lang-btn");
  langBtn.textContent = lang === "en" ? "Ar" : "En";
  langBtn.setAttribute("data-lang", lang === "en" ? "ar" : "en");
}

document.addEventListener("DOMContentLoaded", () => {
  const savedLang = localStorage.getItem("language") || "en";
  updateContent(savedLang);
  document.querySelector(".lang-btn").addEventListener("click", () => {
    const currentLang = document.querySelector(".lang-btn").getAttribute("data-lang");
    updateContent(currentLang);
    localStorage.setItem("language", currentLang);
  });
});